---
kind: pipeline
name: compatibility
steps:
- name: check-app-compatbility
  pull: default
  image: nextcloudci/php7.0:php7.0-19
  commands:
  - wget https://raw.githubusercontent.com/nextcloud/travis_ci/master/before_install.sh
  - bash ./before_install.sh $APP_NAME $CORE_BRANCH $DB
  - cd ../server
  - ./occ app:check-code $APP_NAME -c strong-comparison
  - ./occ app:check-code $APP_NAME -c deprecation
  - cd apps/$APP_NAME/
  environment:
    APP_NAME: issuetemplate
    CORE_BRANCH: stable15
    DB: sqlite
trigger:
  branch:
    - master
    - stable*
  event:
    - pull_request
    - push
---
kind: pipeline
name: syntax-php7.0
steps:
- name: syntax-php7.0
  pull: default
  image: nextcloudci/php7.0:php7.0-19
  commands:
  - wget https://raw.githubusercontent.com/nextcloud/travis_ci/master/before_install.sh
  - bash ./before_install.sh $APP_NAME $CORE_BRANCH $DB
  - cd ../server
  - composer install
  - ./lib/composer/bin/parallel-lint --exclude lib/composer/jakub-onderka/ --exclude 3rdparty/symfony/polyfill-php70/Resources/stubs/ --exclude 3rdparty/patchwork/utf8/src/Patchwork/Utf8/Bootup/ --exclude 3rdparty/paragonie/random_compat/lib/ --exclude lib/composer/composer/autoload_static.php --exclude 3rdparty/composer/autoload_static.php .
  environment:
    APP_NAME: issuetemplate
    CORE_BRANCH: stable15
    DB: sqlite
trigger:
  branch:
    - master
    - stable*
  event:
    - pull_request
    - push
---
kind: pipeline
name: php7.0
steps:
- name: php7.0
  pull: default
  image: nextcloudci/php7.0:php7.0-17
  commands:
  - wget https://raw.githubusercontent.com/nextcloud/travis_ci/master/before_install.sh
  - bash ./before_install.sh $APP_NAME $CORE_BRANCH $DB
  - cd ../server/
  - php occ app:enable issuetemplate
  - cd apps/$APP_NAME
  - make test
  environment:
    APP_NAME: issuetemplate
    CORE_BRANCH: stable15
    DB: sqlite
trigger:
  branch:
    - master
    - stable*
  event:
    - pull_request
    - push
---
kind: pipeline
name: php7.1
steps:
- name: php7.1
  pull: default
  image: nextcloudci/php7.1:php7.1-15
  commands:
  - wget https://raw.githubusercontent.com/nextcloud/travis_ci/master/before_install.sh
  - bash ./before_install.sh $APP_NAME $CORE_BRANCH $DB
  - cd ../server/
  - php occ app:enable issuetemplate
  - cd apps/$APP_NAME
  - make test
  environment:
    APP_NAME: issuetemplate
    CORE_BRANCH: stable15
    DB: sqlite
trigger:
  branch:
    - master
    - stable*
  event:
    - pull_request
    - push
---
kind: pipeline
name: php7.2
steps:
- name: php7.2
  pull: default
  image: nextcloudci/php7.2:php7.2-9
  commands:
  - wget https://raw.githubusercontent.com/nextcloud/travis_ci/master/before_install.sh
  - bash ./before_install.sh $APP_NAME $CORE_BRANCH $DB
  - cd ../server/
  - php occ app:enable issuetemplate
  - cd apps/$APP_NAME
  - make test
  environment:
    APP_NAME: issuetemplate
    CORE_BRANCH: stable15
    DB: sqlite
trigger:
  branch:
    - master
    - stable*
  event:
    - pull_request
    - push
